# Generated by Django 3.2.9 on 2022-06-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randwalk_website', '0003_slider_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=50)),
                ('cus_designation', models.CharField(max_length=50, null=True)),
                ('message', models.TextField(max_length=200)),
                ('cus_image', models.ImageField(upload_to='')),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
