# Generated by Django 3.2.9 on 2022-07-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randwalk_website', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=200)),
                ('long_description', models.TextField(max_length=2000)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_thumbnail', models.ImageField(null=True, upload_to='')),
                ('product_icon', models.ImageField(null=True, upload_to='')),
                ('product_desc_images', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
