# Generated by Django 3.2.9 on 2022-07-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randwalk_website', '0007_projectimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='product_desc_images',
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitle',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
