# Generated by Django 3.2.9 on 2022-07-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randwalk_website', '0008_auto_20220711_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
