# Generated by Django 3.2.9 on 2022-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randwalk_website', '0010_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='designation',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='facebook_profile_link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='instagram_profile_link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin_profile_link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter_profile_link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
