# Generated by Django 3.2.9 on 2022-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randwalk_website', '0011_auto_20220721_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='facebook_profile_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='instagram_profile_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='linkedin_profile_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter_profile_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
