# Generated by Django 3.2.9 on 2023-02-10 17:24

from django.db import migrations, models
from ..enums import PublicationType


class Migration(migrations.Migration):

    dependencies = [
        ('randwalk_website', '0014_alter_project_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('BOOK', 'Book'), ('JOURNAL', 'Journal'), ('PUBLICATION', 'Publication')], default=PublicationType['PUBLICATION'], max_length=20),
        ),
    ]
