# Generated by Django 3.2.9 on 2023-08-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randwalk_website', '0017_alter_publication_detailed_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('details', models.TextField(max_length=500)),
                ('link', models.CharField(max_length=250)),
            ],
        ),
    ]
